export const colors = {
  surface: '#FCF8FF',
  surfaceDim: '#DBD8E8',
  surfaceBright: '#FCF8FF',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F5F2FF',
  surfaceContainer: '#EFECFC',
  surfaceContainerHigh: '#E9E6F6',
  surfaceContainerHighest: '#E3E0F1',
  onSurface: '#1B1B26',
  onSurfaceVariant: '#474555',
  inverseSurface: '#302F3B',
  inverseOnSurface: '#F2EFFF',
  outline: '#777587',
  outlineVariant: '#C8C4D8',
  surfaceTint: '#5141E6',
  primary: '#422CD8',
  onPrimary: '#FFFFFF',
  primaryContainer: '#5B4CF0',
  onPrimaryContainer: '#E8E4FF',
  inversePrimary: '#C4C0FF',
  secondary: '#0061A4',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#47A5FF',
  onSecondaryContainer: '#003964',
  tertiary: '#005C3D',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#007751',
  onTertiaryContainer: '#83FFC5',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  primaryFixed: '#E3DFFF',
  primaryFixedDim: '#C4C0FF',
  onPrimaryFixed: '#130068',
  onPrimaryFixedVariant: '#381DCF',
  secondaryFixed: '#D2E4FF',
  secondaryFixedDim: '#9FCAFF',
  onSecondaryFixed: '#001D36',
  onSecondaryFixedVariant: '#00497D',
  tertiaryFixed: '#7BFAC0',
  tertiaryFixedDim: '#5DDDA5',
  onTertiaryFixed: '#002113',
  onTertiaryFixedVariant: '#005236',
  background: '#FCF8FF',
  onBackground: '#1B1B26',
  surfaceVariant: '#E3E0F1',
  success: '#1FAE7A',
  warning: '#F2A94E',
  // Legacy aliases used across existing screens
  backgroundSecondary: '#F5F2FF',
  border: '#C8C4D8',
  textPrimary: '#1B1B26',
  textSecondary: '#474555',
  textDisabled: '#777587',
  primaryPressed: '#422CD8',
  secondaryBright: '#47A5FF',
  splashBackground: '#FCF8FF',
} as const;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  xxxl: 48,
  gutter: 16,
  marginMobile: 20,
  marginDesktop: 40,
} as const;

export const radius = {
  sm: 4,
  md: 8,
  lg: 16,
  xl: 24,
  card: 28,
  thumbnail: 20,
  pill: 9999,
  button: 12,
  sheet: 24,
} as const;

export const typography = {
  displayLg: {
    fontSize: 48,
    lineHeight: 56,
    fontWeight: '700' as const,
    letterSpacing: -0.96,
  },
  headlineLg: {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: '600' as const,
    letterSpacing: -0.32,
  },
  headlineMd: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600' as const,
  },
  headlineSm: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600' as const,
  },
  headlineLgMobile: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600' as const,
  },
  bodyLg: {
    fontSize: 18,
    lineHeight: 28,
    fontWeight: '400' as const,
  },
  bodyMd: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400' as const,
  },
  labelLg: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600' as const,
    letterSpacing: 0.1,
  },
  labelMd: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500' as const,
  },
  // Legacy aliases
  display: {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '600' as const,
  },
  h1: {
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '600' as const,
  },
  h2: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '600' as const,
  },
  body: {
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '400' as const,
  },
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500' as const,
  },
  button: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600' as const,
  },
};

export const touchTarget = 48;

export const glass = {
  cardBackground: 'rgba(255, 255, 255, 0.72)',
  cardBorder: 'rgba(255, 255, 255, 0.4)',
  inputBackground: 'rgba(255, 255, 255, 0.3)',
} as const;
